spring.application.name=payment-service-springboot

server.port=${SERVER_PORT:5001}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.appo.payment=INFO

grpc.server.port=${GRPC_SERVER_PORT:9091}


